name: Build packages

on:
  push:
    tags:
      - v*

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build rapiex and luci-app-rapiex
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          tags: rapiex:ci

      - name: Create Docker container
        run: docker create --name rapiex rapiex:ci

      - name: Copy files from Docker container
        run: |
          mkdir -p ./bin
          docker cp rapiex:/builder/bin/packages/x86_64/utilites/. ./bin/
          docker cp rapiex:/builder/bin/packages/x86_64/luci/. ./bin/

      - name: Filter IPK files
        run: |
          # Извлекаем версию из тега, убирая префикс 'v'
          VERSION=${GITHUB_REF#refs/tags/v}

          mkdir -p ./filtered-bin
          cp ./bin/luci-i18n-rapiex-ru_*.ipk "./filtered-bin/luci-i18n-rapiex-ru_${VERSION}.ipk"
          cp ./bin/rapiex_*.ipk ./filtered-bin/
          cp ./bin/luci-app-rapiex_*.ipk ./filtered-bin/

      - name: Remove Docker container
        run: docker rm rapiex

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: ./filtered-bin/*.ipk
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
